### ISSUE TITLE
README.rst problem

### ISSUE THREAD

**Issue by Neustradamus** [horazont/aiosasl#11]
https://github.com/horazont/aiosasl/blob/devel/README.rst;
- SCRAM-SHA-1, SCRAM-SHA-224, , SCRAM-SHA-512, SCRAM-SHA-384, and SCRAM-SHA-256: Salted Challenge Response Authentication (RFC 5802), (and the -PLUS variants with channel binding).

Maybe good to have in order...

**Comment by Neustradamus** [comment]
@horazont: Any news? The README is always bad since a very long time.

Good order:
- SCRAM-SHA-1, SCRAM-SHA-224, SCRAM-SHA-256, SCRAM-SHA-384, and SCRAM-SHA-512 will be better.

**Comment by Neustradamus** [comment]
@horazont: It is not possible to re-add other SCRAM for projects which are not XMPP for have all SCRAM-SHA-2 family?
- SCRAM-SHA-224
- SCRAM-SHA-384
- SCRAM-SHA-512

Maybe good to add SCRAM-SHA-3 family too?

**Comment by horazont** [comment]
They (SCRAM-SHA-{224,384,512} or SCRAM-SHA-3) do not exist: https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml

See also #6. We do not support inofficial algorithms in this project.
