### ISSUE TITLE
PyPi still shows unsupported SASL mechanisms

### ISSUE THREAD

**Issue by SamWhited** [horazont/aiosasl#13]
Unspecified SASL mechanisms were removed in #6, but are still listed on https://pypi.org/project/aiosasl/.

**Comment by horazont** [comment]
@SamWhited In #6, we forgot to update the readme (see #11). To update the description on pypi, we have to put out a new release… (you cannot edit the description separately).

**Comment by horazont** [comment]
@SamWhited Thanks, fixed by making a point release.
