### ISSUE TITLE
Please add SCRAM-SHA-512(-PLUS) again and there is the SCRAM-SHA3-512(-PLUS)

### ISSUE THREAD

**Issue by Neustradamus** [horazont/aiosasl#17]
Following the removal of SCRAM-SHA-512(-PLUS), I request you the addition and there is SCRAM-SHA3-512(-PLUS) in the same time.

SCRAM-SHA-512(-PLUS):
- https://tools.ietf.org/html/draft-melnikov-scram-sha-512

SCRAM-SHA3-512(-PLUS):
- https://tools.ietf.org/html/draft-melnikov-scram-sha3-512

A lot of projects have already SCRAM-SHA-512: https://www.google.com/search?q=SCRAM-SHA-512

**Comment by horazont** [comment]
Not yet: https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml#scram
