### ISSUE TITLE
Problems with ManageSieve

### ISSUE THREAD

**Issue by sebastianriese** [horazont/aiosasl#2]
The SASL layer in ManageSieve allows variation as to how client initial data and server final responses are encoded on the protocol layer. The variants for final server responses are (with the example from [RFC 5804](https://tools.ietf.org/html/rfc5804#section-2.1) edited to show only the variation relevant for this issue):
 
       C: Authenticate "DIGEST-MD5"
       S: "cmVhbG09ImVsd29vZC5pbm5vc29mdC5leGFtcGxlLmNvbSIsbm9uY2U9Ik
          9BNk1HOXRFUUdtMmhoIixxb3A9ImF1dGgiLGFsZ29yaXRobT1tZDUtc2Vz
          cyxjaGFyc2V0PXV0Zi04"
       C: "Y2hhcnNldD11dGYtOCx1c2VybmFtZT0iY2hyaXMiLHJlYWxtPSJlbHdvb2
          QuaW5ub3NvZnQuZXhhbXBsZS5jb20iLG5vbmNlPSJPQTZNRzl0RVFHbTJo
          aCIsbmM9MDAwMDAwMDEsY25vbmNlPSJPQTZNSFhoNlZxVHJSayIsZGlnZX
          N0LXVyaT0ic2lldmUvZWx3b29kLmlubm9zb2Z0LmV4YW1wbGUuY29tIixy
          ZXNwb25zZT1kMzg4ZGFkOTBkNGJiZDc2MGExNTIzMjFmMjE0M2FmNyxxb3
          A9YXV0aA=="
       S: OK (SASL "cnNwYXV0aD1lYTQwZjYwMzM1YzQyN2I1NTI3Yjg0ZGJhYmNkZ
          mZmZA==")

or equivalently

       C: Authenticate "DIGEST-MD5"
       S: "cmVhbG09ImVsd29vZC5pbm5vc29mdC5leGFtcGxlLmNvbSIsbm9uY2U9Ik
          9BNk1HOXRFUUdtMmhoIixxb3A9ImF1dGgiLGFsZ29yaXRobT1tZDUtc2Vz
          cyxjaGFyc2V0PXV0Zi04"
       C: "Y2hhcnNldD11dGYtOCx1c2VybmFtZT0iY2hyaXMiLHJlYWxtPSJlbHdvb2
          QuaW5ub3NvZnQuZXhhbXBsZS5jb20iLG5vbmNlPSJPQTZNRzl0RVFHbTJo
          aCIsbmM9MDAwMDAwMDEsY25vbmNlPSJPQTZNSFhoNlZxVHJSayIsZGlnZX
          N0LXVyaT0ic2lldmUvZWx3b29kLmlubm9zb2Z0LmV4YW1wbGUuY29tIixy
          ZXNwb25zZT1kMzg4ZGFkOTBkNGJiZDc2MGExNTIzMjFmMjE0M2FmNyxxb3
          A9YXV0aA=="
       S: "cnNwYXV0aD1lYTQwZjYwMzM1YzQyN2I1NTI3Yjg0ZGJhYmNkZmZmZA=="
       C: ""
       S: OK

That is, the final response by the server may be encoded either as a further challenge (which expects an empty response) or in the status code of the success message. (Similarly, initial data sent by the client is equivalent to the response to an empty query; this, however, poses no problem, since we control the first message and can choose to always send client initial data were the SASL mechanism allows it).

It is impossible for a `SASLInterface` implementation for the protocol to distinguish these cases correctly, without intricate knowledge of the SASL mechanism that is run. I believe that one solution for this problem is to make the `SASLMechanism` implementations themselves robust against this kind of variation. The preferred solution would be to adapt the protocol used by aiosasl internally to communicate with the mechanisms (by not allowing payloads on ``success`` messages and doing the packing/unpacking on the `SASLInterface` layer) and let the mechanisms speak the expanded form of the protocol (which is then unpacked from the wire form by the `SASLInterface` if necessary).

**Comment by horazont** [comment]
Is this expansion of the final message specified in some SASL RFC or is this a specifity to the ManageSieve protocol? It certainly hasn’t happened to me yet in the XMPP context.

**Comment by sebastianriese** [comment]
Both variants are specified in [RFC 4422](https://tools.ietf.org/html/rfc4422); Section 3 The Authentication Exchange lists both possibilities, in particular
>  Where the mechanism specifies that the server is to return additional data to the client with a successful outcome and this field is unavailable or unused, the additional data is sent as a challenge whose response is empty.  After receiving this response, the server then indicates the successful outcome.

**Comment by horazont** [comment]
In that case, we need to support this. Care to draft a change for the interface?
